Fix potential package name conflict when launching app
Running `launch_magmap` by `python magmap/io/load_env.py` or through a subprocess leads to the error: `ImportError: cannot import name 'version' from 'packaging'`. When launching `load_env` these ways, the sub-package is placed at the top of the path. The error arises from a naming conflict with the `packaging` package installed with Pip since now the `magmap.io.packaging` module takes precedence. As a workaround, remove this directory from the path if it matches the path's first entry.